name: flowtrack
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  syncfusion_flutter_charts: ^30.1.37
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.20.2
  uuid: ^4.5.1
  provider: ^6.1.2

  cupertino_icons: ^1.0.8
  flutter_colorpicker: ^1.1.0
  path_provider: ^2.1.5
  csv: ^6.0.0  
  shared_preferences: ^2.5.3
  share_plus: ^11.1.0
  file_picker: ^10.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1
  build_runner: ^2.5.4

flutter:
  uses-material-design: true
  assets:
    - images/